<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="x13" ignored="0" name="Default test" tests="6" failures="1" timestamp="01 Oct 2024 09:07:08 GMT" time="6.184" errors="0">
  <testcase name="test02" time="0.028" classname="org.test.Sample">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase name="test02" time="0.015" classname="org.test.Sample">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase name="test02" time="0.011" classname="org.test.Sample">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase name="test02" time="0.013" classname="org.test.Sample">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase name="test02" time="0.011" classname="org.test.Sample">
    <skipped/>
  </testcase> <!-- test02 -->
  <testcase name="test02" time="0.02" classname="org.test.Sample">
    <failure type="java.lang.AssertionError" message="expected [adactin.com - Hotel Reservation System] but found [Adactin.com - Hotel Reservation System]">
      <![CDATA[java.lang.AssertionError: expected [adactin.com - Hotel Reservation System] but found [Adactin.com - Hotel Reservation System]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.test.Sample.test02(Sample.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- test02 -->
</testsuite> <!-- Default test -->
